version: '3.8'

services:
  scraper-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: PlaywrightAPI
    restart: unless-stopped
    ports:
      - "8001:8000"
    volumes:
      - ./app:/app/app
    environment:
      - TZ=Asia/Tokyo
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
